// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-2",
    "aws_cognito_identity_pool_id": "us-east-2:a529a93a-2203-44c6-b4c1-e4ad8cf5470a",
    "aws_cognito_region": "us-east-2",
    "aws_user_pools_id": "us-east-2_M7XVXcEjl",
    "aws_user_pools_web_client_id": "5j55ho3uu30lrbspadr6pr67r0",
    "oauth": {},
    "aws_appsync_graphqlEndpoint": "https://5tcxkerh3nbi7epe6ippmjtnue.appsync-api.us-east-2.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-2",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-je7gzhds6zfcxjxhruzm2ocjhq",
    "redirectSignIn": "http://localhost:3000",
    "redirectSignOut": "http://localhost:3000/"
};


export default awsmobile;
